env:
  es6: true
  node: true
  jest/globals: true
extends:
  - "eslint:recommended"
  - "plugin:import/errors"
  - "plugin:import/warnings"
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    sourceType: module
    allowImportExportEverywhere: false
plugins:
  - jest
rules:
  indent: [error, 2, SwitchCase: 1]
  linebreak-style: [error, unix]
  quotes: [2, single]
  semi: [error, never]
  strict: [2, never]

